/*
 * 도메인
 * 
 * CM - 공통(COMMON)
 * BL - 블로그(BLOG)
 * RS - 이력서(RESUME)
 * 
 * */


-- 공통
CREATE TABLE cm_menu_m (
    menu_id VARCHAR(20) NOT NULL COMMENT '메뉴ID',
    menu_nm VARCHAR(100) NOT NULL COMMENT '메뉴명',
    parent_menu_id VARCHAR(20) NULL COMMENT '부모메뉴ID',
    menu_url VARCHAR(200) NULL COMMENT '메뉴URL',
    sort_no INT DEFAULT 0 COMMENT '정렬순서',
    menu_lv INT DEFAULT 1 COMMENT '메뉴레벨',
    icon_nm VARCHAR(50) NULL COMMENT '아이콘클래스명',
    use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

    CONSTRAINT pk_cm_menu_m PRIMARY KEY (menu_id),
    CONSTRAINT fk_cm_menu_upr FOREIGN KEY (upr_menu_id) REFERENCES cm_menu_m (menu_id)
) COMMENT = '메뉴원장';

CREATE TABLE cm_cd_m (
	cm_cd VARCHAR(20) NOT NULL COMMENT '공통코드',
	cm_cd_nm VARCHAR(100) NOT NULL COMMENT '공통코드명',
	rmrk VARCHAR(500) NULL COMMENT '비고',
	use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

	CONSTRAINT pk_cm_cd_m PRIMARY KEY (cm_cd)
) COMMENT = '공통코드원장';

CREATE TABLE cm_cd_d (
	cm_cd VARCHAR(20) NOT NULL COMMENT '공통코드',
	dtl_cd VARCHAR(20) NOT NULL COMMENT '상세코드',
	dtl_cd_nm VARCHAR(100) NOT NULL COMMENT '상세코드명',
	rmrk VARCHAR(500) NULL COMMENT '비고',
	use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

	CONSTRAINT pk_cm_cd_d PRIMARY KEY (cm_cd, dtl_cd),
	CONSTRAINT fk_cm_cd_d_01 FOREIGN KEY (cm_cd) 
		REFERENCES cm_cd_m (cm_cd)
) COMMENT = '공통코드상세';


-- 블로그
CREATE TABLE bl_src_m (
	src_cd VARCHAR(20) NOT NULL COMMENT '출처코드',
	src_nm VARCHAR(100) NOT NULL COMMENT '출처명',
	src_tp_cd VARCHAR(20) NOT NULL COMMENT '출처유형코드',
	src_url VARCHAR(500) NULL COMMENT '출처URL',
	src_logo_url VARCHAR(500) NULL COMMENT '출처로고URL',
	use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

	CONSTRAINT pk_bl_src_m PRIMARY KEY (src_cd)
) COMMENT = '출처원장';

CREATE TABLE cm_stg_word_m (
    stg_word_id VARCHAR(20) NOT NULL COMMENT '표준단어id',
    stg_word_nm VARCHAR(200) NOT NULL COMMENT '표준단어명',
    stg_word_eng_nm VARCHAR(200) NULL COMMENT '표준단어영문명',
    stg_word_eng_abbr_nm VARCHAR(20) NULL COMMENT '표준단어영문약어명',
    stg_word_dfn TEXT NULL COMMENT '표준단어정의',
    stg_word_src VARCHAR(100) COMMENT '표준단어출처',
    use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

    CONSTRAINT pk_cm_stg_word_m PRIMARY KEY (stg_word_id),
    CONSTRAINT uk_cm_stg_word_nm UNIQUE (stg_word_nm),
    CONSTRAINT uk_cm_stg_word_eng_abbr_nm UNIQUE (stg_word_eng_abbr_nm)
) COMMENT = '표준단어원장';


CREATE TABLE bl_pstg_m (
	pstg_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '게시글ID',
	src_cd VARCHAR(20) NOT NULL COMMENT '회사코드',
	pstg_ttl VARCHAR(300) NOT NULL COMMENT '게시글제목',
	pstg_thmb_url VARCHAR(500) NULL COMMENT '게시글썸네일URL',
	pstg_dttm DATETIME NOT NULL COMMENT '게시일시',
	use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
	
	CONSTRAINT fk_bl_pstg_m_01 FOREIGN KEY (src_cd) 
		REFERENCES bl_src_m (src_cd) 
		ON DELETE CASCADE
) COMMENT = '게시글원장';

CREATE TABLE bl_pstg_vw_cnt_m (
	pstg_id BIGINT PRIMARY KEY COMMENT '게시글ID',
	pstg_vw_cnt BIGINT NOT NULL DEFAULT 0 COMMENT '게시글조회수',
	reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

	CONSTRAINT fk_bl_pstg_vw_cnt_m_01 FOREIGN KEY (pstg_id) REFERENCES bl_pstg_m (pstg_id)
) COMMENT = '게시글 조회수';


CREATE TABLE bl_pstg_d (
	pstg_id BIGINT NOT NULL COMMENT '게시글ID',
	pstg_smry TEXT NULL COMMENT '게시글요약', /* JSON */
	pstg_url VARCHAR(1000) NOT NULL COMMENT '게시글URL',
	use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

	CONSTRAINT pk_bl_pstg_d PRIMARY KEY (pstg_id),
	CONSTRAINT fk_bl_pstg_d_01 FOREIGN KEY (pstg_id) 
		REFERENCES bl_pstg_m (pstg_id) 
		ON DELETE CASCADE
) COMMENT = '게시글상세';

CREATE TABLE bl_tag_m (
	tag_cd BIGINT AUTO_INCREMENT COMMENT '태그코드',
	tag_nm VARCHAR(100) NOT NULL COMMENT '태그명',
	use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

	CONSTRAINT pk_bl_tag_m PRIMARY KEY (tag_cd)
) COMMENT='태그원장'

CREATE TABLE bl_pstg_tag_r (
	pstg_id BIGINT NOT NULL COMMENT '게시글ID',
	tag_cd BIGINT NOT NULL COMMENT '태그ID',
	use_yn CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	reg_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	mod_dttm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

	CONSTRAINT pk_bl_pstg_tag_r PRIMARY KEY (pstg_id, tag_cd),
	CONSTRAINT fk_bl_pstg_tag_r_01 FOREIGN KEY (pstg_id) 
		REFERENCES bl_pstg_m (pstg_id) 
		ON DELETE CASCADE,
	CONSTRAINT fk_bl_pstg_tag_r_02 FOREIGN KEY (tag_cd) 
		REFERENCES bl_tag_m (tag_cd)
) COMMENT='게시글태그관계'
